services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=notely-spring'
      - 'POSTGRES_PASSWORD=debug'
      - 'POSTGRES_USER=debug'
    ports:
      - '5432'
  notely-spring:
    build: .
    image: eclipse-temurin:23-jdk
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notely-spring
      SPRING_DATASOURCE_USERNAME: debug
      SPRING_DATASOURCE_PASSWORD: debug